60 Correção no backend.
fga-eps-mds/2020-2-SiGeD-Users pull request #9
Opened 2021-03-11 20:02 UTC by DaviMarinho

Issue: fga-eps-mds/2020-2-G4#60

## Descrição:

Corrigido os nomes de usuário.
Rotas com nomes padronizados.
Funções modularizadas.
Todos os emails são únicos.

2021-03-11 21:03 UTC, gabibguedes requested changes
Faltam algumas correções.

2021-03-11 21:03 UTC, gabibguedes commented on src/Models/UserSchema.js
> +userSchema.set('timestamps', true);
O horário está errado, creio que está sendo adicionado o horário em UTC. O horário deve ser o horário local.

2021-03-11 21:03 UTC, gabibguedes commented on src/Utils/validate.js
> +const validateRole = (role) => {
A validação de role deve ser se a string passada é `admin`, `professional` ou `receptionist`. O role não pode ser qualquer string.

2021-03-12 13:13 UTC, DaviMarinho commented on src/Models/UserSchema.js
> +userSchema.set('timestamps', true);
Feito

2021-03-12 13:13 UTC, DaviMarinho commented on src/Utils/validate.js
> +const validateRole = (role) => {
Feito

2021-03-12 15:00 UTC, gabibguedes requested changes
Utilize funções do JS para fazer a validação do role, ao invés de usar o for para varrer o array

2021-03-12 15:00 UTC, gabibguedes commented on src/Utils/validate.js
> +  valid.push('admin');
Como são só 3 strings, é melhor colocar direto no array, do que ir adicionando um por um. 
```js
const valid = ['admin','professional', 'receptionist' ];
```

2021-03-12 15:00 UTC, gabibguedes commented on src/Utils/validate.js
> +  for (let i = 0; i < valid.length; i + 1) {
Não é necessário fazer essa verificação por for. No JS já tem função pra verificar se a string está no array, é a função includes, ai usaria dessa forma:

```js
valid.includes(role)
```
Ao invés de fazer o for e colocar 1 ou 0 em uma variável, você pode fazer a verificação direto no if.

```js
  if (valid.includes(role)) {
    return true;
  }
  return false;
```

2021-03-12 15:19 UTC, DaviMarinho commented on src/Utils/validate.js
> +  valid.push('admin');
Feito

2021-03-12 15:19 UTC, DaviMarinho commented on src/Utils/validate.js
> +  for (let i = 0; i < valid.length; i + 1) {
Feito (muito mais simples assim, obrigado kkkkk)

2021-03-12 15:31 UTC, gabibguedes approved these changes
Ok

2021-03-12 15:32 UTC, merged